### category - list
GET http://127.0.0.1:8000/api/v1/categories/ HTTP/1.1
content-type: application/json


### category - create
POST http://127.0.0.1:8000/api/v1/categories/ HTTP/1.1
content-type: application/json

{
    "name": "new category name",
    "slug": "newcategory",
    "description": "new category description"
}


### category - destroy
DELETE  http://127.0.0.1:8000/api/v1/categories/5/ HTTP/1.1
content-type: application/json


### genre - list
GET http://127.0.0.1:8000/api/v1/genres/ HTTP/1.1
content-type: application/json


### genre - create
POST http://127.0.0.1:8000/api/v1/genres/ HTTP/1.1
content-type: application/json

{
    "name": "new genre name",
    "slug": "newgenre",
    "description": "new genre description"
}


### genre - destroy
DELETE  http://127.0.0.1:8000/api/v1/genres/16/ HTTP/1.1
content-type: application/json


### title - list
GET http://127.0.0.1:8000/api/v1/titles/ HTTP/1.1
content-type: application/json


### title - create
POST http://127.0.0.1:8000/api/v1/titles/ HTTP/1.1
content-type: application/json

{
    "name": "new title",
    "year": 1981,
    "category": 1
}


### title - destroy
DELETE  http://127.0.0.1:8000/api/v1/titles/33/ HTTP/1.1
content-type: application/json


### review - list
GET http://127.0.0.1:8000/api/v1/reviews/ HTTP/1.1
content-type: application/json


### review - create
POST http://127.0.0.1:8000/api/v1/reviews/ HTTP/1.1
content-type: application/json

{
    "text": "new review text",
    "score": 9,
    "title": 1,
    "author": 1
}


### review - destroy
DELETE  http://127.0.0.1:8000/api/v1/reviews/76/ HTTP/1.1
content-type: application/json


### comments - list
GET http://127.0.0.1:8000/api/v1/comments/ HTTP/1.1
content-type: application/json


### comment - create
POST http://127.0.0.1:8000/api/v1/comments/ HTTP/1.1
content-type: application/json

{
    "text": "new comment text",
    "review": 1,
    "author": 1
}


### comment - destroy
DELETE  http://127.0.0.1:8000/api/v1/comments/4/ HTTP/1.1
content-type: application/json
